# 2D Costmap parameters
# http://www.ros.org/wiki/costmap_2d

### Coordinate frame and tf parameters ###
robot_base_frame:           segway/base_link
transform_tolerance:        1.5

# ---RMPOMNI footprint (Meters):---
footprint: [[0.7875, -0.3945], [0.7875, 0.3945],[-0.7875, 0.3945],[-0.7875, -0.3945],[0.7875, -0.3945]]

# The following parameter is overwritten if the "footprint" parameter is set
#robot_radius:               0.325

### Costmap layer definitions ###
publish_frequency:           1.0
plugins:                     []

static:
  unknown_cost_value:        -1
  lethal_cost_threshold:     100
  map_topic:                 map
  subscribe_to_updates:      true

obstacles_costmap2d:
  observation_sources: segway_scan
  segway_scan: {topic:                   segway/filtered_scan,
                data_type:               LaserScan,
                marking:                 true,
                clearing:                true,
                obstacle_range:          19.0,
                raytrace_range:          20.0}

obstacles_voxel_grid:
  origin_z:              0.0
  z_resolution:          0.2
  z_voxels:              10
  unknown_threshold:     5
  mark_threshold:        0
  publish_voxel_map:     false
  observation_sources: segway_point_cloud
  segway_point_cloud: {topic:                   segway/filtered_points2,
                       data_type:               PointCloud2,
                       expected_update_rate:    0.5,
                       observation_persistence: 0.0,
                       marking:                 true,
                       clearing:                true,
                       inf_is_valid:            false,
                       min_obstacle_height:     0.0,
                       max_obstacle_height:     2.0,
                       obstacle_range:          5.5,
                       raytrace_range:          6.0}

inflation:
  inflation_radius:           0.2  #default 0.5
  cost_scaling_factor:        10.0 #default 10.0

